[project_cfg]
name = "MetaFarm"

[api]
port = ":80"
max_num = 500
session_ttl = 86400

[log]
compress = false
leep_days = 7
level = "info"
mode = "console"
path = "logs/v1-backend"
service_name = "v1-backend"

[[kv.redis]]
pass = "123456"
host = "127.0.0.1:6379"
type = "node"

[db]
database = "meta_farm"
host = "127.0.0.1"
user = "meta_farm"
password = "1qaz!QAZ"
port = 3306 #4000
max_open_conns = 1500
log_level = "info"
max_conn_max_lifetime = 300
max_idle_conns = 10

[[chain_supported]]
name="sepolia"
chain_id=11155111
endpoint = "https://rpc.ankr.com/eth_sepolia"

[easyswap_market]
apikey = ""
name = "EasySwap"
version= "1"
contract= "0x1466ceE9XXXXXXXXXXXXXXXXXXXcD4"
fee=100

[image_cfg]
valid_file_type = [".jpeg", ".gif", ".png", ".mp4", ".jpg", ".glb", ".gltf", ".mp3", ".wav", ".svg"]
time_out = 40
public_ipfs_gateways = ["https://gateway.pinata.cloud/ipfs/","https://cf-ipfs.com/ipfs/","https://ipfs.infura.io/ipfs/","https://ipfs.pixura.io/ipfs/","https://ipfs.io/ipfs/","https://www.via0.com/ipfs/"]
local_ipfs_gateways = ["https://gateway.pinata.cloud/ipfs/","https://cf-ipfs.com/ipfs/","https://ipfs.infura.io/ipfs/","https://ipfs.pixura.io/ipfs/","https://ipfs.io/ipfs/","https://www.via0.com/ipfs/"]
default_oss_uri = "https://test.easyswap.link/"

[metadata_parse]
name_tags = ["name", "title"]
image_tags = ["image", "image_url", "animation_url", "media_url", "image_data", "imageUrl"]
attributes_tags = ["attributes", "properties", "attribute"]
trait_name_tags = ["trait_type"]
trait_value_tags = ["value"]

[ethereum]
rpc_url = "https://mainnet.infura.io/v3/your-api-key"  # 以太坊RPC地址
private_key = "0xyour-private-key"                     # 以太坊私钥（生产环境建议使用环境变量）

[zksync]
rpc_url = "https://mainnet.era.zksync.io"              # zkSync RPC地址
private_key = "0xyour-private-key"                     # zkSync私钥（与以太坊私钥保持一致）
bridge_address = "0x32400084C286CF3E17e7B677ea9583e60a000324"  # zkSync官方桥接合约地址
